server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_mp3
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Taille max fichier MP3 uploadé
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB